doctrine:
  dbal:
    driver: "oci8"
    server_version: "19c"
    default_table_options:
      charset: AL32UTF8
    host: "exaccdfdev-scan.saude.gov" # Nome do container do Oracle no Docker
    port: 1521
    dbname: "DFDO1.saude.gov" # Nome do PDB correto (verificado pelo `lsnrctl status`)
    user: "PETINFOSDWEB"
    password: "K7iPOIsPAi9D9aVU"
    service: true

  orm:
    auto_generate_proxy_classes: "%kernel.debug%"
    naming_strategy: doctrine.orm.naming_strategy.underscore
    auto_mapping: true
    quote_strategy: App\Doctrine\ORM\Mapping\CustomQuoteStrategy
    mappings:
      App:
        is_bundle: false
        type: annotation
        dir: "%kernel.project_dir%/src/Entity"
        prefix: 'App\Entity'
        alias: App
