version: "3.8"

services:
  app:
    build: .
    container_name: symfony_app
    restart: always
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    ports:
      - "9000:9000" # PHP-FPM
      - "8000:8000" # Symfony Server para desenvolvimento
