<?php

namespace AppBundle\Repository;

/**
 * AreaTematicaGrupoAtuacaoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AreaTematicaGrupoAtuacaoRepository extends RepositoryAbstract
{
}
