<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Instituicao;

/**
 * CampusInstituicaoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CampusInstituicaoRepository extends RepositoryAbstract
{
    /**
     * @param Instituicao $instituicao
     * @param boolean $returnArrayResult
     * @return \AppBundle\Entity\CampusInstituicao[] | array
     */
    public function findByInstituicao(Instituicao $instituicao, $returnArrayResult = true)
    {
        $qb = $this->createQueryBuilder('c');
        $qb
            ->select('c.noCampus, c.coSeqCampusInstituicao, pj.nuCnpj')
            ->join('c.instituicao', 'i')
            ->join('i.pessoaJuridica', 'pj')
            ->andWhere("c.stRegistroAtivo = 'S'")
            ->andWhere('identity(c.instituicao) = :instituicao')
            ->setParameter('instituicao', $instituicao->getCoSeqInstituicao())
            ->orderBy('c.noCampus', 'asc');
        
        if ($returnArrayResult) {
            return $qb->getQuery()->getArrayResult();
        }
        
        return $qb->getQuery()->getResult();
    }        
}
