<?php

namespace AppBundle\Repository;

/**
 * CategoriaProfissionalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoriaProfissionalRepository extends RepositoryAbstract
{
}
