<?php

namespace AppBundle\Repository;

/**
 * CepRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CepRepository extends RepositoryAbstract
{
}
