<?php

namespace AppBundle\Repository;

/**
 * EnderecoWebRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnderecoWebRepository extends RepositoryAbstract
{
}
