<?php

namespace AppBundle\Repository;

/**
 * IdentidadeGeneroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IdentidadeGeneroRepository extends RepositoryAbstract
{
}
