<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Municipio;

/**
 * InstituicaoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InstituicaoRepository extends RepositoryAbstract
{
    /**
     * @param Municipio $municipio
     * @param boolean $returnArrayResult
     * @return \AppBundle\Entity\Instituicao[] | array
     */
    public function findByMunicipio(Municipio $municipio, $returnArrayResult = true)
    {
        $qb = $this->createQueryBuilder('i');
        $qb
            ->select('i, pj')
            ->join('i.pessoaJuridica', 'pj')
            ->andWhere("i.stRegistroAtivo = 'S'")
            ->andWhere('identity(i.municipio) = :municipio')
            ->setParameter('municipio', $municipio->getCoMunicipioIbge())
            ->orderBy('i.noInstituicaoProjeto', 'asc');
        
        if ($returnArrayResult) {
            return $qb->getQuery()->getArrayResult();
        }
        
        return $qb->getQuery()->getResult();
    }    
}
