<?php

namespace AppBundle\Repository;

/**
 * IntegracaoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IntegracaoRepository extends RepositoryAbstract
{
}
