<?php

namespace AppBundle\Repository;

/**
 * NaturezaJuridicaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NaturezaJuridicaRepository extends RepositoryAbstract
{
}
