<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Perfil;

/**
 * PerfilRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PerfilRepository extends RepositoryAbstract
{
    /**
     * @param string $noRole
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function getDisponiveisParaCadastroDeParticipante($noRole)
    {
        $qb = $this->createQueryBuilder('p');
        $qb->where('p.stRegistroAtivo = \'S\'')
           ->orderBy('p.dsPerfil', 'ASC');
        
        if ($noRole == Perfil::ROLE_ADMINISTRADOR) {
            $qb->andWhere('p.coSeqPerfil = 2');
        } else {
            $qb->andWhere('p.coSeqPerfil not in( 1,2 )');
        }
        
        return $qb;
    }
}
