<?php

namespace AppBundle\Repository;

/**
 * PessoaGeneroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PessoaGeneroRepository extends RepositoryAbstract
{
}
