<?php

namespace AppBundle\Repository;

/**
 * ProjetoEstabelecimentoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjetoEstabelecimentoRepository extends RepositoryAbstract
{
}
