<?php

namespace AppBundle\Repository;

/**
 * ProjetoCampusInstituicaoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjetoCampusInstituicaoRepository extends RepositoryAbstract
{
}
