<?php

namespace AppBundle\Repository;

/**
 * ProjetoPessoaCursoGraduacaoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjetoPessoaCursoGraduacaoRepository extends RepositoryAbstract
{
}
