<?php

namespace AppBundle\Repository;

/**
 * QuantidadePublicacaoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuantidadePublicacaoRepository extends RepositoryAbstract
{
}
