<?php

namespace AppBundle\Repository;

/**
 * SituacaoProjetoFolhaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SituacaoProjetoFolhaRepository extends RepositoryAbstract
{
    /**
     * @return \AppBundle\Entity\SituacaoProjetoFolha
     */
    public function getSituacaoAutorizada()
    {
        return $this->find(\AppBundle\Entity\SituacaoProjetoFolha::AUTORIZADA);
    }
}
