<?php

namespace AppBundle\Repository;

/**
 * TextoSaudacaoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TextoSaudacaoRepository extends RepositoryAbstract
{
}