<?php

namespace AppBundle\Repository;

/**
 * TipoQuantitativoPublicacaoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoQuantitativoPublicacaoRepository extends RepositoryAbstract
{
}
