<?php

namespace AppBundle\Repository;

/**
 * TipoAreaTematicaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoAreaTematicaRepository extends RepositoryAbstract
{
}
