<?php

namespace AppBundle\Repository;

/**
 * UfRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UfRepository extends RepositoryAbstract
{
}
