imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: webservices.yml }
    - { resource: repositories.yml }
    - { resource: listeners.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: pt_BR
    upload_directory: "%kernel.root_dir%/../web/uploads"

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~
    

# Twig Configuration
twig:
    form_themes:
        - 'bootstrap_3_layout.html.twig'
    debug:            "%kernel.debug%"
    strict_variables: false

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_service_name%"
        user:     "%database_user%"
        password: "%database_password%"
        service:  "%database_service_use%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        quote_strategy: app.doctrine_orm.quote_strategy

        metadata_cache_driver: array
        query_cache_driver: array
        result_cache_driver: array

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# Assetic Configuration
assetic:
    debug:          '%kernel.debug%'
    use_controller: '%kernel.debug%'
    filters:
        cssrewrite: ~

knp_paginator:
    page_range: 5                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: KnpPaginatorBundle:Pagination:twitter_bootstrap_v3_pagination.html.twig     # sliding pagination controls template
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig # sort link template

knp_menu:
    twig:
        template: knp_menu.html.twig
    templating: false
    default_renderer: twig

services:
    oracle.listener:
        class: Doctrine\DBAL\Event\Listeners\OracleSessionInit
        tags:
            - { name: doctrine.event_listener, event: postConnect }
    #oracle.role_listener:
    #    class: AppBundle\Doctrine\Event\Listeners\RoleListener
    #    calls:
    #        - [setRoleName, ["%database_role_name%"]]
    #        - [setRolePass, ["%database_role_pass%"]]
    #    tags:
    #        - { name: doctrine.event_listener, event: postConnect }
#    twig.extension.intl:
#        class: Twig_Extensions_Extension_Intl
#        tags:
#            - { name: twig.extension }
    oracle.auditoria_listener:
        class: AppBundle\Doctrine\Event\Listeners\AuditoriaListener
        arguments: ["@request_stack", "@session"]
        tags:
            - { name: doctrine.event_listener, event: postConnect, connection: default}
    security.authentication.switchuser_listener:
        class: AppBundle\EventListener\SwitchUserListener
        public: false
        abstract: true
        arguments: ["@security.token_storage", "", "@security.user_checker", "", "@security.access.decision_manager", "@?logger", "_switch_user", "ROLE_ALLOWED_TO_SWITCH", "@?event_dispatcher", "ROLE_SWITCHABLE"]
        tags:
            - { name: monolog.logger, channel: security }            
    app.impersonate_listener:
        class: AppBundle\Doctrine\Event\Listeners\ImpersonateListener
        arguments: ["@security.token_storage"]
        tags:
            - { name: doctrine.event_listener, event: preFlush }

tactician:
    commandbus:
        default:
            middleware:
                # service ids for all your middlewares, top down. First in, first out.
                - tactician.middleware.validator
                - tactician.middleware.doctrine
                - tactician.middleware.locking
                - tactician.middleware.command_handler