<?php

namespace App\Repository;

use App\Entity\Projeto;
use App\Entity\AreaTematica;
use App\Repository\RepositoryAbstract;
use Doctrine\Persistence\ManagerRegistry;

/**
 * AreaTematicaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AreaTematicaRepository extends RepositoryAbstract
{
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, AreaTematica::class);
    }

    /**
     * @param Projeto $projeto
     * @return \App\Entity\AreaTematica
     */
    public function findTipoAreaTematicaByProjeto(Projeto $projeto)
    {
        $qb = $this->createQueryBuilder('at');
        $qb
            ->select('ga.coSeqGrupoAtuacao, tat.dsTipoAreaTematica')
            ->join('at.tipoAreaTematica', 'tat')
            ->join('at.areasTematicasGruposAtuacao', 'atga')
            ->join('atga.grupoAtuacao', 'ga')
            ->where('at.projeto = :projeto')
            ->setParameter('projeto', $projeto->getCoSeqProjeto())
            ->andWhere('at.stRegistroAtivo = \'S\'')
            ->orderBy('tat.dsTipoAreaTematica', 'ASC');
        
        return $qb->getQuery()->getArrayResult();
    }
}
