<?php

namespace App\Repository;

use PDO;
use App\Entity\Banco;
use App\Entity\AgenciaBancaria;
use App\Repository\RepositoryAbstract;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Component\HttpFoundation\ParameterBag;

/**
 * BancoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BancoRepository extends RepositoryAbstract
{
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, AgenciaBancaria::class);
    }

    /**
     *
     * @param ParameterBag $pb
     * @return Doctrine\ORM\Query
     */
    public function findByFilter(ParameterBag $pb)
    {
        $qb = $this->createQueryBuilder('b');
        $qb->select('b');
        $qb->andWhere('b.dtRemocao IS NULL');

        if (!is_null($pb->get('coBanco'))) {
            $qb->andWhere('b.coBanco LIKE :coBanco');
            $qb->setParameter('coBanco', $pb->get('coBanco') . '%', \PDO::PARAM_STR);
        }

        if (!is_null($pb->get('noBanco'))) {
            $qb->andWhere('b.noBanco LIKE :noBanco');
            $qb->setParameter('noBanco', '%' . $pb->get('noBanco') . '%', \PDO::PARAM_STR);
        }

        if (!is_null($pb->get('stRegistroAtivo'))) {
            $qb->andWhere('b.stRegistroAtivo = :stAtivo');
            $qb->setParameter('stAtivo', $pb->get('stRegistroAtivo'), \PDO::PARAM_STR);
        }

        $this->orderPagination($qb, $pb);

        return $qb->getQuery();
    }

    public function merge(Banco $banco) {
        $this->getEntityManager()->merge($banco); // MERGE not PERSIST
        $this->getEntityManager()->flush();
    }

}