<?php

namespace App\Repository;

/**
 * CboOcupacaoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CboOcupacaoRepository extends RepositoryAbstract
{
}