<?php

namespace App\Repository;

/**
 * CursoGraduacaoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CursoGraduacaoRepository extends RepositoryAbstract
{
}
