<?php

namespace App\Repository;

/**
 * DadoAcademicoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DadoAcademicoRepository extends RepositoryAbstract
{
}
