<?php

namespace App\Repository;

/**
 * OrgaoEmissorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrgaoEmissorRepository extends RepositoryAbstract
{
}
