<?php

namespace App\Repository;

/**
 * PessoaPerfilRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PessoaPerfilRepository extends RepositoryAbstract
{
}
