<?php

namespace App\Repository;

use App\Entity\ProjetoPessoaCursoGraduacao;
use App\Repository\RepositoryAbstract;
use Doctrine\Persistence\ManagerRegistry;

/**
 * ProjetoPessoaCursoGraduacaoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjetoPessoaCursoGraduacaoRepository extends RepositoryAbstract
{
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, ProjetoPessoaCursoGraduacao::class);
    }
}
