<?php

namespace App\Repository;

use App\Entity\ProjetoCampusInstituicao;
use App\Repository\RepositoryAbstract;
use Doctrine\Persistence\ManagerRegistry;

/**
 * ProjetoCampusInstituicaoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjetoCampusInstituicaoRepository extends RepositoryAbstract
{
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, ProjetoCampusInstituicao::class);
    }
}
