<?php

namespace App\Repository;

/**
 * SecretariaSaudeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SecretariaSaudeRepository extends RepositoryAbstract
{
}
