<?php

namespace App\Repository;

/**
 * SituacaoProjetoFolhaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SituacaoProjetoFolhaRepository extends RepositoryAbstract
{
    /**
     * @return \App\Entity\SituacaoProjetoFolha
     */
    public function getSituacaoAutorizada()
    {
        return $this->find(\App\Entity\SituacaoProjetoFolha::AUTORIZADA);
    }
}
