<?php

namespace App\Repository;

/**
 * TelefoneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TelefoneRepository extends RepositoryAbstract
{
}
