<?php

namespace App\Repository;

/**
 * TitulacaoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TitulacaoRepository extends RepositoryAbstract
{
}
