<?php

namespace App\Repository;

use App\Entity\AgenciaBancaria;
use App\Entity\Titulacao;
use Doctrine\Persistence\ManagerRegistry;

/**
 * TitulacaoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TitulacaoRepository extends RepositoryAbstract
{
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, Titulacao::class);
    }
}
