monolog:
  handlers:
    main:
      type: fingers_crossed
      action_level: error
      handler: nested
    nested:
      type: stream
      path: "%kernel.logs_dir%/%kernel.environment%.log"
      level: debug
    console:
      type: console
    mail:
      type: fingers_crossed
      # 500 errors are logged at the critical level
      action_level: critical
      # to also log 400 level errors (but not 404's):
      # action_level: error
      # excluded_404s:
      #     - ^/
      handler: buffered
    buffered:
      type: buffer
      handler: swift
    swift:
      type: swift_mailer
      from_email: "info.sgtes@saude.gov.br"
      to_email: ["emmanuel.garcia@saude.gov.br", "pauloe.oliveira@saude.gov.br"]
      # or list of recipients
      # to_email:   ['dev1@example.com', 'dev2@example.com', ...]
      subject: An Error Occurred!
      level: debug
