services:
    app.send_mail_fale_conosco_listener:
        class: AppBundle\EventListener\SendMailFaleConoscoListener
        arguments: ["@mailer", "@templating"]
        tags:
            - { name: kernel.event_subscriber }
    
    app.handle_vigencia_bolsa_programa_listener:
        class: AppBundle\EventListener\HandleVigenciaBolsaProgramaListener
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
            
    app.send_mail_notificacao_formulario_avaliacao_atividade:
        class: AppBundle\EventListener\SendMailNotificacaoFormularioAvaliacaoAtividadeListener
        arguments: ["@mailer", "@templating", "@app.tramitacao_formulario_repository"]
        tags:
            - { name: kernel.event_subscriber }
    
    app.send_mail_notificacao_analise_retorno_formulario_avaliacao_atividade:
        class: AppBundle\EventListener\SendMailNotificacaoAnaliseRetornoFormularioAvaliacaoAtividadeListener
        arguments: ["@mailer", "@templating"]
        tags:
            - { name: kernel.event_subscriber }
            
    app.send_mail_notificacao_exclusao_envio_formulario_avaliacao_atividade:
        class: AppBundle\EventListener\SendMailNotificacaoExcusaoEnvioFormularioAvaliacaoAtividadeListener
        arguments: ["@mailer", "@templating"]
        tags:
            - { name: kernel.event_subscriber }

    app.handle_situacao_grupo_atuacao:
        class: AppBundle\EventListener\HandleSituacaoGrupoAtuacaoListener
        arguments: ["@app.grupo_atuacao_repository"]
        tags:
            - { name: kernel.event_subscriber }
