services:
  app.send_mail_fale_conosco_listener:
    class: App\EventListener\SendMailFaleConoscoListener
    arguments: ["@mailer", "@twig"]
    tags:
      - { name: kernel.event_subscriber }

  app.handle_vigencia_bolsa_programa_listener:
    class: App\EventListener\HandleVigenciaBolsaProgramaListener
    arguments: ["@doctrine.orm.entity_manager"]
    tags:
      - {
          name: kernel.event_listener,
          event: kernel.controller,
          method: onKernelController,
        }

  app.send_mail_notificacao_formulario_avaliacao_atividade:
    class: App\EventListener\SendMailNotificacaoFormularioAvaliacaoAtividadeListener
    arguments: ["@mailer", "@twig", "@app.tramitacao_formulario_repository"]
    tags:
      - { name: kernel.event_subscriber }

  app.send_mail_notificacao_analise_retorno_formulario_avaliacao_atividade:
    class: App\EventListener\SendMailNotificacaoAnaliseRetornoFormularioAvaliacaoAtividadeListener
    arguments: ["@mailer", "@twig"]
    tags:
      - { name: kernel.event_subscriber }

  app.send_mail_notificacao_exclusao_envio_formulario_avaliacao_atividade:
    class: App\EventListener\SendMailNotificacaoExcusaoEnvioFormularioAvaliacaoAtividadeListener
    arguments: ["@mailer", "@twig"]
    tags:
      - { name: kernel.event_subscriber }

  app.handle_situacao_grupo_atuacao:
    class: App\EventListener\HandleSituacaoGrupoAtuacaoListener
    arguments: ["@app.grupo_atuacao_repository"]
    tags:
      - { name: kernel.event_subscriber }
