# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
  app.usuario_repository:
    class: Doctrine\ORM\EntityRepository
    factory: ["@doctrine.orm.default_entity_manager", getRepository]
    arguments:
      - App\Entity\Usuario

  app.programa_repository:
    class: Doctrine\ORM\EntityRepository
    factory: ["@doctrine.orm.default_entity_manager", getRepository]
    arguments:
      - App\Entity\Programa

  app.tipo_quantitativo_publicacao_repository:
    class: Doctrine\ORM\EntityRepository
    factory: ["@doctrine.orm.default_entity_manager", getRepository]
    arguments:
      - App\Entity\TipoQuantitativoPublicacao

  app.publicacao_repository:
    class: Doctrine\ORM\EntityRepository
    factory: ["@doctrine.orm.default_entity_manager", getRepository]
    arguments:
      - App\Entity\Publicacao

  app.projeto_pessoa_repository:
    class: Doctrine\ORM\EntityRepository
    factory: ["@doctrine.orm.default_entity_manager", getRepository]
    arguments:
      - App\Entity\ProjetoPessoa

  app.pessoa_perfil_repository:
    class: Doctrine\ORM\EntityRepository
    factory: ["@doctrine.orm.default_entity_manager", getRepository]
    arguments:
      - App\Entity\PessoaPerfil

  app.texto_saudacao_repository:
    class: Doctrine\ORM\EntityRepository
    factory: ["@doctrine.orm.default_entity_manager", getRepository]
    arguments:
      - App\Entity\TextoSaudacao

  app.projeto_repository:
    class: Doctrine\ORM\EntityRepository
    factory: ["@doctrine.orm.default_entity_manager", getRepository]
    arguments:
      - App\Entity\Projeto

  app.municipio_repository:
    class: Doctrine\ORM\EntityRepository
    factory: ["@doctrine.orm.default_entity_manager", getRepository]
    arguments:
      - App\Entity\Municipio

  app.dado_pessoal_repository:
    class: Doctrine\ORM\EntityRepository
    factory: ["@doctrine.orm.default_entity_manager", getRepository]
    arguments:
      - App\Entity\DadoPessoal

  app.instituicao_repository:
    class: Doctrine\ORM\EntityRepository
    factory: ["@doctrine.orm.default_entity_manager", getRepository]
    arguments:
      - App\Entity\Instituicao

  app.campus_instituicao_repository:
    class: Doctrine\ORM\EntityRepository
    factory: ["@doctrine.orm.default_entity_manager", getRepository]
    arguments:
      - App\Entity\CampusInstituicao

  app.pessoa_juridica_repository:
    class: Doctrine\ORM\EntityRepository
    factory: ["@doctrine.orm.default_entity_manager", getRepository]
    arguments:
      - App\Entity\PessoaJuridica

  app.pessoa_fisica_repository:
    class: Doctrine\ORM\EntityRepository
    factory: ["@doctrine.orm.default_entity_manager", getRepository]
    arguments:
      - App\Entity\PessoaFisica

  app.tipo_area_tematica_repository:
    class: Doctrine\ORM\EntityRepository
    factory: ["@doctrine.orm.default_entity_manager", getRepository]
    arguments:
      - App\Entity\TipoAreaTematica

  app.area_tematica_repository:
    class: Doctrine\ORM\EntityRepository
    factory: ["@doctrine.orm.default_entity_manager", getRepository]
    arguments:
      - App\Entity\AreaTematica

  app.grupo_atuacao_repository:
    class: Doctrine\ORM\EntityRepository
    factory: ["@doctrine.orm.default_entity_manager", getRepository]
    arguments:
      - App\Entity\GrupoAtuacao

  app.endereco_repository:
    class: Doctrine\ORM\EntityRepository
    factory: ["@doctrine.orm.default_entity_manager", getRepository]
    arguments:
      - App\Entity\Endereco

  app.curso_graduacao_repository:
    class: Doctrine\ORM\EntityRepository
    factory: ["@doctrine.orm.default_entity_manager", getRepository]
    arguments:
      - App\Entity\CursoGraduacao

  app.titulacao_repository:
    class: Doctrine\ORM\EntityRepository
    factory: ["@doctrine.orm.default_entity_manager", getRepository]
    arguments:
      - App\Entity\Titulacao

  app.cbo_ocupacao_repository:
    class: Doctrine\ORM\EntityRepository
    factory: ["@doctrine.orm.default_entity_manager", getRepository]
    arguments:
      - App\Entity\CboOcupacao

  app.identidade_genero_repository:
    class: Doctrine\ORM\EntityRepository
    factory: ["@doctrine.orm.default_entity_manager", getRepository]
    arguments:
      - App\Entity\IdentidadeGenero

  app.perfil_repository:
    class: Doctrine\ORM\EntityRepository
    factory: ["@doctrine.orm.default_entity_manager", getRepository]
    arguments:
      - App\Entity\Perfil

  app.orgao_emissor_repository:
    class: Doctrine\ORM\EntityRepository
    factory: ["@doctrine.orm.default_entity_manager", getRepository]
    arguments:
      - App\Entity\OrgaoEmissor

  app.uf_repository:
    class: Doctrine\ORM\EntityRepository
    factory: ["@doctrine.orm.default_entity_manager", getRepository]
    arguments:
      - App\Entity\Uf

  app.estado_civil_repository:
    class: Doctrine\ORM\EntityRepository
    factory: ["@doctrine.orm.default_entity_manager", getRepository]
    arguments:
      - App\Entity\EstadoCivil

  app.banco_repository:
    class: Doctrine\ORM\EntityRepository
    factory: ["@doctrine.orm.default_entity_manager", getRepository]
    arguments:
      - App\Entity\Banco

  app.agencia_bancaria_repository:
    class: Doctrine\ORM\EntityRepository
    factory: ["@doctrine.orm.default_entity_manager", getRepository]
    arguments:
      - App\Entity\AgenciaBancaria

  app.projeto_estabelecimento_repository:
    class: Doctrine\ORM\EntityRepository
    factory: ["@doctrine.orm.default_entity_manager", getRepository]
    arguments:
      - App\Entity\ProjetoEstabelecimento

  app.categoria_profissional_repository:
    class: Doctrine\ORM\EntityRepository
    factory: ["@doctrine.orm.default_entity_manager", getRepository]
    arguments:
      - App\Entity\CategoriaProfissional

  app.cep_repository:
    class: Doctrine\ORM\EntityRepository
    factory: ["@doctrine.orm.default_entity_manager", getRepository]
    arguments:
      - App\Entity\Cep

  app.folha_pagamento_repository:
    class: Doctrine\ORM\EntityRepository
    factory: ["@doctrine.orm.default_entity_manager", getRepository]
    arguments:
      - App\Entity\FolhaPagamento

  app.projeto_folha_pagamento_repository:
    class: Doctrine\ORM\EntityRepository
    factory: ["@doctrine.orm.default_entity_manager", getRepository]
    arguments:
      - App\Entity\ProjetoFolhaPagamento

  app.autorizacao_folha_repository:
    class: Doctrine\ORM\EntityRepository
    factory: ["@doctrine.orm.default_entity_manager", getRepository]
    arguments:
      - App\Entity\AutorizacaoFolha

  app.situacao_projeto_folha_repository:
    class: Doctrine\ORM\EntityRepository
    factory: ["@doctrine.orm.default_entity_manager", getRepository]
    arguments:
      - App\Entity\SituacaoProjetoFolha

  app.situacao_folha_repository:
    class: Doctrine\ORM\EntityRepository
    factory: ["@doctrine.orm.default_entity_manager", getRepository]
    arguments:
      - App\Entity\SituacaoFolha

  app.integracao_repository:
    class: Doctrine\ORM\EntityRepository
    factory: ["@doctrine.orm.default_entity_manager", getRepository]
    arguments:
      - App\Entity\Integracao

  app.endereco_web_repository:
    class: Doctrine\ORM\EntityRepository
    factory: ["@doctrine.orm.default_entity_manager", getRepository]
    arguments:
      - App\Entity\EnderecoWeb

  app.telefone_repository:
    class: Doctrine\ORM\EntityRepository
    factory: ["@doctrine.orm.default_entity_manager", getRepository]
    arguments:
      - App\Entity\Telefone

  app.projeto_pessoa_grupo_atuacao_repository:
    class: Doctrine\ORM\EntityRepository
    factory: ["@doctrine.orm.default_entity_manager", getRepository]
    arguments:
      - App\Entity\ProjetoPessoaGrupoAtuacao

  app.vw_folha_pagamento_repository:
    class: Doctrine\ORM\EntityRepository
    factory: ["@doctrine.orm.default_entity_manager", getRepository]
    arguments:
      - App\Entity\VwFolhaPagamento

  app.vw_grupoatuacao_qtprofissional_repository:
    class: Doctrine\ORM\EntityRepository
    factory: ["@doctrine.orm.default_entity_manager", getRepository]
    arguments:
      - App\Entity\VwGrupoatuacaoQtprofissional

  app.vw_participante:
    class: Doctrine\ORM\EntityRepository
    factory: ["@doctrine.orm.default_entity_manager", getRepository]
    arguments:
      - App\Entity\VwParticipante

  app.participante_folhapagamento_repository:
    class: Doctrine\ORM\EntityRepository
    factory: ["@doctrine.orm.default_entity_manager", getRepository]
    arguments:
      - App\Entity\ParticipanteFolhapagamento

  app.tramitacao_situacao_folha_repository:
    class: Doctrine\ORM\EntityRepository
    factory: ["@doctrine.orm.default_entity_manager", getRepository]
    arguments:
      - App\Entity\TramitacaoSituacaoFolha

  app.fale_conosco_repository:
    class: Doctrine\ORM\EntityRepository
    factory: ["@doctrine.orm.default_entity_manager", getRepository]
    arguments:
      - App\Entity\FaleConosco

  app.valor_bolsa_programa_repository:
    class: Doctrine\ORM\EntityRepository
    factory: ["@doctrine.orm.default_entity_manager", getRepository]
    arguments:
      - App\Entity\ValorBolsaPrograma

  app.emissao_certificado_repository:
    class: Doctrine\ORM\EntityRepository
    factory: ["@doctrine.orm.default_entity_manager", getRepository]
    arguments:
      - App\Entity\EmissaoCertificado

  app.modelo_certificado_repository:
    class: Doctrine\ORM\EntityRepository
    factory: ["@doctrine.orm.default_entity_manager", getRepository]
    arguments:
      - App\Entity\ModeloCertificado

  app.planejamento_ano_folha_repository:
    class: Doctrine\ORM\EntityRepository
    factory: ["@doctrine.orm.default_entity_manager", getRepository]
    arguments:
      - App\Entity\PlanejamentoAnoFolha

  app.planejamento_mes_folha_repository:
    class: Doctrine\ORM\EntityRepository
    factory: ["@doctrine.orm.default_entity_manager", getRepository]
    arguments:
      - App\Entity\PlanejamentoMesFolha

  app.formulario_avaliacao_atividade_repository:
    class: Doctrine\ORM\EntityRepository
    factory: ["@doctrine.orm.default_entity_manager", getRepository]
    arguments:
      - App\Entity\FormularioAvaliacaoAtividade

  app.envio_formulario_avaliacao_atividade_repository:
    class: Doctrine\ORM\EntityRepository
    factory: ["@doctrine.orm.default_entity_manager", getRepository]
    arguments:
      - App\Entity\EnvioFormularioAvaliacaoAtividade

  app.situacao_tramite_formulario_repository:
    class: Doctrine\ORM\EntityRepository
    factory: ["@doctrine.orm.default_entity_manager", getRepository]
    arguments:
      - App\Entity\SituacaoTramiteFormulario

  app.tramitacao_formulario_repository:
    class: Doctrine\ORM\EntityRepository
    factory: ["@doctrine.orm.default_entity_manager", getRepository]
    arguments:
      - App\Entity\TramitacaoFormulario

  app.autoriza_cadastro_participante_repository:
    class: Doctrine\ORM\EntityRepository
    factory: ["@doctrine.orm.default_entity_manager", getRepository]
    arguments:
      - App\Entity\AutorizaCadastroParticipante

  app.retorno_pagamento_repository:
    class: Doctrine\ORM\EntityRepository
    factory: ["@doctrine.orm.default_entity_manager", getRepository]
    arguments:
      - App\Entity\RetornoPagamento

  app.cabecalho_arquivo_retorno_pagamento_repository:
    class: Doctrine\ORM\EntityRepository
    factory: ["@doctrine.orm.default_entity_manager", getRepository]
    arguments:
      - App\Entity\CabecalhoArquivoRetornoPagamento

  app.detalhe_arquivo_retorno_pagamento_repository:
    class: Doctrine\ORM\EntityRepository
    factory: ["@doctrine.orm.default_entity_manager", getRepository]
    arguments:
      - App\Entity\DetalheArquivoRetornoPagamento

  app.rodape_arquivo_retorno_pagamento_repository:
    class: Doctrine\ORM\EntityRepository
    factory: ["@doctrine.orm.default_entity_manager", getRepository]
    arguments:
      - App\Entity\RodapeArquivoRetornoPagamento

  app.retorno_criacao_conta_repository:
    class: Doctrine\ORM\EntityRepository
    factory: ["@doctrine.orm.default_entity_manager", getRepository]
    arguments:
      - App\Entity\RetornoCriacaoConta

  app.cabecalho_retorno_criacao_conta_repository:
    class: Doctrine\ORM\EntityRepository
    factory: ["@doctrine.orm.default_entity_manager", getRepository]
    arguments:
      - App\Entity\CabecalhoRetornoCriacaoConta

  app.detalhe_retorno_criacao_conta_repository:
    class: Doctrine\ORM\EntityRepository
    factory: ["@doctrine.orm.default_entity_manager", getRepository]
    arguments:
      - App\Entity\DetalheRetornoCriacaoConta

  app.rodape_retorno_criacao_conta_repository:
    class: Doctrine\ORM\EntityRepository
    factory: ["@doctrine.orm.default_entity_manager", getRepository]
    arguments:
      - App\Entity\RodapeRetornoCriacaoConta

  app.projeto_pessoa_area_tematica_grupo_atuacao_repository:
    class: Doctrine\ORM\EntityRepository
    factory: ["@doctrine.orm.default_entity_manager", getRepository]
    arguments:
      - App\Entity\ProjetoPessoaAreaTematicaGrupoAtuacao
